name: Build AppImage

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.32.1"

jobs:
  build_appimage:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev libnotify-dev wget file

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(sed -n 's/^version: \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' pubspec.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build AppImage
        run: |
          chmod +x build_appimage.sh
          ./build_appimage.sh

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: appimage-x86_64
          path: ./*.AppImage

      - name: Test AppImage
        run: |
          # Make sure the AppImage was created and is executable
          ls -la *.AppImage
          file *.AppImage
