name: Release Linux (Flutter)

on:
  push:
    branches: [release] # altere se usar outro branch de release

permissions:
  contents: write # necessário para criar/alterar Releases

env:
  APP_NAME: flow_focus

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, aarch64]

    steps:
      - uses: actions/checkout@v4

      # Dependências do Flutter desktop + local_notifier
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev \
            libnotify-dev libdbus-1-dev

      # Flutter SDK para build x64
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Configure Flutter
        run: |
          flutter config --enable-linux-desktop
          flutter pub get

      # BUILD PARA X64 NATIVO
      - name: Build for x64
        if: matrix.arch == 'x64'
        run: flutter build linux --release

      # BUILD PARA ARM64 VIA QEMU + Docker (multi-arch)
      - name: Enable QEMU for multi-arch
        if: matrix.arch == 'aarch64'
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Build for aarch64 using Docker
        if: matrix.arch == 'aarch64'
        run: |
          docker run --rm -t --platform linux/arm64 \
            -v $PWD:/app -w /app \
            cirrusci/flutter:stable \
            bash -c "flutter config --enable-linux-desktop && flutter pub get && flutter build linux --release --target-platform=linux-arm64"

      # EMPACOTAMENTO DOS BINÁRIOS
      - name: Package release binary
        run: |
          ARCH_FOLDER=${{ matrix.arch == 'x64' && 'x64' || 'arm64' }}
          cd build/linux/$ARCH_FOLDER/release
          tar -czf "$APP_NAME-linux-${{ matrix.arch }}.tar.gz" bundle
          mv "$APP_NAME-linux-${{ matrix.arch }}.tar.gz" "$GITHUB_WORKSPACE/"

      # UPLOAD PARA A PRÓXIMA ETAPA
      - uses: actions/upload-artifact@v4
        with:
          name: linux-binary-${{ matrix.arch }}
          path: ${{ env.APP_NAME }}-linux-${{ matrix.arch }}.tar.gz
          retention-days: 3

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-binary-x64
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: linux-binary-aarch64
          path: .

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: linux-${{ github.run_number }}
          name: "Linux Build ${{ github.run_number }}"
          generate_release_notes: true
          files: |
            ${{ env.APP_NAME }}-linux-x64.tar.gz
            ${{ env.APP_NAME }}-linux-aarch64.tar.gz
