name: Build Linux (amd64 and arm64)

on:
  push:
    branches: [main, release]

env:
  APP_NAME: flow_focus
  FLUTTER_VERSION: 3.32.1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu liblzma-dev

      # 3. Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          channel: stable
          cache: true
          cache-key: "flutter-${{ runner.os }}-${{ env.FLUTTER_VERSION }}-${{ hashFiles('**/pubspec.lock') }}" # More specific cache key

      # 4. Enable desktop target
      - run: flutter config --enable-linux-desktop

      # 5. Get packages
      - run: flutter pub get

      # 6. Build for amd64 (native)
      - name: Build for amd64
        if: matrix.arch == 'amd64'
        run: |
          flutter build linux --release
          mkdir -p dist/amd64
          cp -r build/linux/x64/release/bundle/* dist/amd64/

      # 7. Cross-compile for arm64
      - name: Cross-compile for arm64
        if: matrix.arch == 'arm64'
        run: |
          flutter build bundle
          mkdir -p build/linux/arm64/release/bundle

          # Run cmake manually with toolchain
          cd linux
          cmake -B build-arm64 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
            -DFLUTTER_TARGET_PLATFORM=linux-arm64 \
            -GNinja

          cmake --build build-arm64

          # Copy binaries + flutter_assets to bundle
          mkdir -p dist/arm64
          cp -r ../build/flutter_assets dist/arm64/
          cp build-arm64/${{ env.APP_NAME }} dist/arm64/

      # 8. Package output
      - name: Package ${{ matrix.arch }}
        run: |
          cd dist/${{ matrix.arch }}
          tar -czvf ../../${{ env.APP_NAME }}-${{ matrix.arch }}.tar.gz .

      # 9. Upload artifact
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-${{ matrix.arch }}
          path: ${{ env.APP_NAME }}-${{ matrix.arch }}.tar.gz
